# Generated by Django 5.2.7 on 2025-10-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
    ]
